all:
	gcc main.cc \
	../src/maze/Model/parser.cc \
	../src/maze/model/pathFinder.cc \
	../src/maze/Controller/controller.cc \
	-std=c++17 -lstdc++
	./a.out

g:
	gcc main.cc \
	../src/maze/Model/parser.cc \
	../src/maze/model/pathFinder.cc \
	../src/maze/Controller/controller.cc \
	-std=c++17 -lstdc++ -g
